######################################################################
##
## Filename: detector_sdft_tb.udo
## Created on: Sat Jan 28 16:42:34 Europa Środkowa (czas stand.) 2017
##
## Auto generated by Project Navigator for Post-Route Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
