######################################################################
##
## Filename: frequencyDetectorTB.udo
## Created on: Mon Jan 23 11:26:02 Europa Środkowa (czas stand.) 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
