######################################################################
##
## Filename: sdft_tb.udo
## Created on: Tue Jan 24 15:55:30 Europa Środkowa (czas stand.) 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
